### ISSUE TITLE
complains about single-digit hours (H:MM:SS)

### ISSUE THREAD

**Issue by jayenashar** [thatsmydoing/gtfs.html#25]
According to the spec: `Times must be eight digits in HH:MM:SS format (H:MM:SS is also accepted, if the hour begins with 0).`

gtfs.html gives errors like `Invalid time: invalid time: 4:44:00 for arrival_time` when it should accept the time.

Also it's a bit weird to say 'invalid time' twice.

**Comment by thatsmydoing** [comment]
H:MM:SS times are now valid
