### ISSUE TITLE
Unable to connect to https://gtfs.pleasantprogrammer.com/ or http://gtfs.pleasantprogrammer.com/

### ISSUE THREAD

**Issue by jayenashar** [thatsmydoing/gtfs.html#26]
:(

**Comment by thatsmydoing** [comment]
Oops, sorry about this. It should be up again.

**Comment by jayenashar** [comment]
thanks!  i ran it locally fine in the meantime.  that waterfall view on the trips screen is really handy!

**Comment by thatsmydoing** [comment]
Thanks! It's nice to know someone else thinks it's useful
