### ISSUE TITLE
gtfs.pleasantprogrammer.com ko ?

### ISSUE THREAD

**Issue by nlehuby** [thatsmydoing/gtfs.html#36]
There is something wrong with the version deployed at gtfs.pleasantprogrammer.com

When you load a new GTFS, you get the following error:
![image](https://user-images.githubusercontent.com/919962/89507237-8a312c00-d7cc-11ea-9f72-40e60d56a579.png)

seems to reproduce with any GTFS

**Comment by jayenashar** [comment]
I confirm the error.  https://gtfs.pleasantprogrammer.com/dist/7581e8bde948919a30c2.worker.js is a 404 Not found

**Comment by thatsmydoing** [comment]
Oh sorry, I've uploaded the missing file.
