### ISSUE TITLE
gtfs.pleasantprogrammer.com ko ?

### ISSUE THREAD

**Issue by jayenashar** [thatsmydoing/gtfs.html#58]
![image](https://user-images.githubusercontent.com/1137152/211229861-1c89f6b0-c770-4e5a-b8fa-e66053e877a6.png)

**Comment by thatsmydoing** [comment]
Oh, good catch. The page is actually on https://gtfs.pleasantprogrammer.com/gtfs.html I've added a redirect from index.html to it
